
name: My Scheduled and Push Trigger

on:
  push:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Script
        run: |
          chmod +x xbwtt0.sh
          ./xbwtt0.sh
